dist: xenial
language: ruby
rvm: 2.5.3
gemfile:
  - Gemfile
sudo: false
before_install: gem install bundler
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
